Solution & Project Update
ruarai/CompilePal pull request #180
Opened 2022-08-24 02:12 UTC by ennerperez

In order to be more consistent with new dotnet project, I suggest some of this solution/project enhancements.

2022-09-11 02:23 UTC, Exactol requested changes
Thank you for cleaning up the code. Everything looks good, but I had a few comments.

Personally I'm not a fan of using var instead of explicit types for most cases, except if the type appears on the right hand side of the assignment. It's fine when using an IDE, but it makes it harder to read if you use a text editor that doesn't display the types, like when looking at the code on GitHub.

2022-09-11 02:23 UTC, Exactol commented on CompilePalX/Updating/UpdateManager.cs
> +        public static event UpdateFound OnUpdateFound;
Move fields before methods

2022-09-20 01:01 UTC, ennerperez commented on CompilePalX/Compilers/BSPPack/AssetUtils.cs
> +            };
![image](https://user-images.githubusercontent.com/1206858/191144669-bd997fac-0b43-42f7-9f2c-cb3f36eefb46.png)

Let's turn explicit types then, sounds good.

2022-10-02 17:47 UTC, ennerperez commented
I have to close this and create new PRs with minor changes to avoid significant conflicts in the future.

2022-10-02 17:47 UTC, closed without merging